services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: toaster
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toaster
    healthcheck:
      test: ["CMD", "pg_isready", "-Utoaster", "-dtoaster"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: postgres
    volumes:
      - ./coverage:/coverage:rw
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
